### ISSUE TITLE
Original videos in banding dataset

### ISSUE THREAD

**Issue by vztu** [akshay-kap/Meng-699-Image-Banding-detection#1]
Hi, 

Thanks for sharing this great work! I'm wondering could you share the original mp4 videos that you used for creating this dataset?

**Comment by duanpanjun** [comment]
> Hi,
> 
> Thanks for sharing this great work! I'm wondering could you share the original mp4 videos that you used for creating this dataset?感谢您分享这部伟大的作品！我想知道您能否分享您用于创建此数据集的原始 mp4 视频？

Hello! Have you found it？
