### ISSUE TITLE
About datasets (quantization process)

### ISSUE THREAD

**Issue by duanpanjun** [akshay-kap/Meng-699-Image-Banding-detection#6]
Hello, I'd like to ask if 'six level quantization' refers to quantization from 6 bits to 8 bits, or if it means six different quantization levels?

**Comment by akshay-kap** [comment]
Hey, you can find this information here in the repository: https://github.com/akshay-kap/Meng-699-Image-Banding-detection/tree/master/Dataset-Generation/Generating-Quantized-frames-from-videos#readme

**Comment by duanpanjun** [comment]
Thank you for your reply, I understand!
